### ISSUE TITLE
Generate typespecs as well

### ISSUE THREAD

**Issue by seivan** [sasa1977/exactor#31]
How would you feel about adding support for typespecs? 

```elixir
  defcast inc(x :: integer), state: state, do: new_state(state + x)
```

would generate

```elixir
@spec inc(x :: integer)
  def inc(pid, x), do: GenServer.cast(pid, {:inc, x})
```

**Comment by sasa1977** [comment]
I think that for your example, I prefer adding the `@spec` manually. The reason is that such approach is consistent with how specs are supplied in other modules.

With your proposal, we'd have to use both "inlined" specs and the explicit ones. In some cases even the ExActor powered modules would need to contain the combination of both styles. I fear that this would cause more confusion and so I'm not sure it's worth supporting this.
